"use strict";
(function(){
const L=window.Landy;
const state={eventAfter:0,protocolAfter:0,events:[],protocol:[],loading:false,hydrating:false,hydrated:false,latestDiagnostics:null,capture:null};
const MAX_UI_EVENTS=40,MAX_UI_FRAMES=24,MAX_EXPORT_PAGES=32;
const exportPause=()=>new Promise(resolve=>setTimeout(resolve,1300));
function timeLabel(value){return typeof value==="number"?`${(value/1000).toFixed(1)} s`:"–"}
function renderSystem(data){if(!data)return;state.latestDiagnostics=data;const status=data.status||{},actual=status.heater?.actual||{},network=status.network?.state||{},station=network.station||{},phase=data.phase11||{};L.definition(L.$("diagnostics-system"),[[L.t("communication"),actual.communication||"–"],[L.t("heaterState"),actual.heater_state||"–"],[L.t("lastStatus"),timeLabel(actual.last_status_ms)],[L.t("station"),station.connected?(station.ip||L.t("online")):L.t("offline")],[L.t("uptime"),timeLabel(data.uptime_ms)],[L.t("freeMemory"),data.heap_free_bytes==null?"–":`${data.heap_free_bytes} B`],[L.t("eventHistory"),`${phase.event_count??0} / ${phase.event_capacity??0}`],[L.t("liveProtocol"),`${phase.protocol_count??0} / ${phase.protocol_capacity??0}`]])}
function renderEvents(){const list=L.$("diagnostics-events");list.replaceChildren();L.text(L.$("diagnostics-event-count"),state.events.length);if(!state.events.length){list.append(L.el("li","empty",L.t("noEvents")));return}state.events.slice().reverse().forEach(value=>{const item=L.el("li"),badge=L.el("span",`badge ${value.severity==="error"?"danger":value.severity==="warning"?"warn":"neutral"}`,L.t(value.severity||"info")),title=L.el("strong",null,value.message||value.code),meta=L.el("span","diagnostic-meta",`${value.category} · ${timeLabel(value.time_ms)} · #${value.sequence}`);item.append(badge,title,meta);if(value.data&&Object.keys(value.data).length)item.append(L.el("code",null,JSON.stringify(value.data)));list.append(item)})}
function renderProtocol(){const list=L.$("diagnostics-protocol");list.replaceChildren();L.text(L.$("diagnostics-protocol-count"),state.protocol.length);if(!state.protocol.length){list.append(L.el("li","empty",L.t("noFrames")));return}state.protocol.slice().reverse().forEach(value=>{const item=L.el("li"),badge=L.el("span",`badge ${value.direction==="rx"?"ok":"neutral"}`,String(value.direction||"–").toUpperCase()),name=L.el("strong",null,value.command_name||value.activity||L.t("unknown")),meta=L.el("span","diagnostic-meta",`${timeLabel(value.time_ms)} · ${value.length} B · CRC ${value.crc_valid==null?"–":value.crc_valid?"OK":"!"}`);item.append(badge,name,meta,L.el("code",null,value.raw_hex||""));list.append(item)})}
function renderCapture(value){state.capture=value||{};const active=Boolean(value?.active),available=Boolean(value?.available),badge=L.$("capture-badge");badge.className=`badge ${active?"warn":available?"ok":"neutral"}`;badge.textContent=L.t(active?"recording":available?"ready":"inactive");L.definition(L.$("capture-status"),[[L.t("captureLabel"),value?.label||"–"],[L.t("status"),badge.textContent],[L.t("records"),String(value?.items_total??0)],[L.t("complete"),value?.complete==null?"–":L.boolean(value.complete)]]);L.$("capture-start").disabled=active;L.$("capture-stop").disabled=!active;L.$("capture-export").disabled=!available;L.$("capture-export-ndjson").disabled=!available}
function mergePage(target,page,maximum){if(page.gap)target.length=0;for(const item of page.items||[])target.push(item);if(target.length>maximum)target.splice(0,target.length-maximum);return page.next_after??0}
async function load(){if(state.loading||L.state.busy||location.hash!=="#diagnostics"||document.hidden)return;state.loading=true;const live=L.$("diagnostics-live");live.className="badge warn";live.textContent=L.t("updating");try{const diagnostics=await L.request(`/api/v1/diagnostics?event_after=${state.eventAfter}&protocol_after=${state.protocolAfter}`);renderSystem(diagnostics.live);state.eventAfter=mergePage(state.events,diagnostics.events||{},MAX_UI_EVENTS);state.protocolAfter=mergePage(state.protocol,diagnostics.protocol_log||{},MAX_UI_FRAMES);renderEvents();renderProtocol();renderCapture(diagnostics.live?.phase11?.capture);live.className="badge ok";live.textContent=L.t("live")}catch(error){live.className="badge danger";live.textContent=L.t("offline")}finally{state.loading=false}}
function download(name,value){const blob=new Blob([JSON.stringify(value,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),0)}
function downloadNdjson(name,value){const header={...value};delete header.items;const lines=[JSON.stringify({type:"capture",...header})];for(const item of value.items||[])lines.push(JSON.stringify(item));const blob=new Blob([`${lines.join("\n")}\n`],{type:"application/x-ndjson"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),0)}
async function allEvents(){let after=0,items=[],metadata=null;for(let pageIndex=0;pageIndex<MAX_EXPORT_PAGES;pageIndex++){const data=(await L.request(`/api/v1/events?after=${after}&limit=16`)).events;metadata={oldest_sequence:data.oldest_sequence,latest_sequence:data.latest_sequence,dropped:data.dropped,gap:data.gap};items.push(...(data.items||[]));after=data.next_after;if(!data.has_more)return{schema:"landy-heater.event-history",version:1,metadata,events:items};await exportPause()}throw new Error(L.t("exportTooLarge"))}
async function allCapture(){let offset=0,header=null,items=[];for(let pageIndex=0;pageIndex<MAX_EXPORT_PAGES;pageIndex++){const value=(await L.request(`/api/v1/capture/export?offset=${offset}&limit=4`)).capture_export;if(!header){header={schema:value.schema,version:value.version,id:value.id,label:value.label,started_ms:value.started_ms,ended_ms:value.ended_ms,complete:value.complete,items_dropped:value.items_dropped,metadata:value.metadata}}items.push(...(value.items||[]));offset+=value.items?.length||0;if(!value.has_more)return{...header,items};await exportPause()}throw new Error(L.t("exportTooLarge"))}
async function action(work,success){if(L.state.busy)return;L.state.busy=true;try{await work();L.toast(L.t(success));await load()}catch(error){L.toast(error.message||L.t("requestFailed"),true)}finally{L.state.busy=false}}
function wire(){L.$("capture-start").addEventListener("click",()=>{const label=L.$("capture-label").value.trim();if(!label||new TextEncoder().encode(label).length>64){L.toast(L.t("captureLabelInvalid"),true);return}action(()=>L.mutate("/api/v1/capture","POST",{label},false),"captureStarted")});L.$("capture-stop").addEventListener("click",()=>action(()=>L.mutate("/api/v1/capture","DELETE",undefined,false),"captureStopped"));L.$("export-diagnostics").addEventListener("click",()=>action(async()=>download("landy-heater-diagnostics.json",await L.request("/api/v1/diagnostics")),"exportReady"));L.$("export-events").addEventListener("click",()=>action(async()=>download("landy-heater-events.json",await allEvents()),"exportReady"));L.$("capture-export").addEventListener("click",()=>action(async()=>download("landy-heater-capture.json",await allCapture()),"exportReady"));L.$("capture-export-ndjson").addEventListener("click",()=>action(async()=>downloadNdjson("landy-heater-capture.ndjson",await allCapture()),"exportReady"))}
async function hydrate(){if(state.hydrated||state.hydrating)return;state.hydrating=true;const holder=L.$("view-diagnostics"),active=holder.classList.contains("active");try{const response=await fetch("/assets/diagnostics.html",{cache:"no-store"});if(!response.ok)throw new Error();const documentCopy=new DOMParser().parseFromString(await response.text(),"text/html"),source=documentCopy.querySelector("#view-diagnostics");if(!source)throw new Error();const surface=document.importNode(source,true);if(active)surface.classList.add("active");holder.replaceWith(surface);surface.querySelectorAll("[data-i18n]").forEach(node=>{node.textContent=L.t(node.dataset.i18n)});wire();state.hydrated=true;setInterval(load,2000);onView(location.hash.slice(1))}catch(error){holder.textContent=L.t("requestFailed");L.setConnection(false)}finally{state.hydrating=false}}
function bind(){}
function onView(name){if(name==="diagnostics"&&!state.hydrated){hydrate();return}const live=L.$("diagnostics-live");if(!live)return;if(name==="diagnostics"){live.className="badge warn";live.textContent=L.t("updating");load()}else{live.className="badge neutral";live.textContent=L.t("paused")}}
L.modules.diagnostics={bind,onView,load,renderEvents,renderProtocol};
})();
