"use strict";
(function(){
const L=window.Landy;
const stateLabel=value=>L.t(value||"unknown");
const targetLabel=requested=>requested?.mode==="power"?`${requested.power_level??"–"} / 9`:requested?.target_temperature==null?"–":`${requested.target_temperature} °C`;
function renderTemperature(role,key){const item=L.state.status?.temperatures?.[role]||{};L.text(L.$(`temp-${key}`),L.temperature(item.value_c));L.text(L.$(`health-${key}`),L.health(item.health))}
function renderNextTimer(value){const node=L.$("next-timer");node.replaceChildren();if(!value){node.className="empty";node.textContent=L.t("noTimer");return}node.className="";const title=L.el("strong",null,value.start||"–");const detail=L.el("p","muted",`${value.timer_id||""} · ${value.minutes_from_now??"–"} ${L.t("minutes")}`);node.append(title,detail)}
function renderWarnings(values){const list=L.$("warnings");list.replaceChildren();const warnings=Array.isArray(values)?values:[];L.text(L.$("warning-count"),warnings.length);if(!warnings.length){list.append(L.el("li","empty",L.t("noWarnings")));return}warnings.forEach(value=>list.append(L.el("li",null,String(value).replaceAll("_"," "))))}
function render(status){if(!status)return;const heater=status.heater||{},actual=heater.actual||{},requested=heater.requested||{},session=heater.session;const actualState=actual.heater_state||"unknown";const active=Boolean(requested.on||session||(actualState!=="off"&&actualState!=="unknown"));const badge=L.$("heater-badge");badge.className=`badge ${actualState==="off"?"neutral":actualState==="running"?"ok":actualState==="unknown"?"danger":"warn"}`;badge.textContent=stateLabel(actualState);L.text(L.$("heater-state"),stateLabel(actualState));L.text(L.$("heater-detail"),heater.control_faulted?L.t("failed"):requested.on?L.mode(requested.mode):L.t("off"));L.text(L.$("remaining"),heater.remaining_seconds==null?"–":L.minutes(Math.ceil(heater.remaining_seconds/60)));L.$("off-actions").classList.toggle("hidden",active);L.$("running-actions").classList.toggle("hidden",!active);L.text(L.$("active-mode"),L.mode(session?.mode||requested.mode));L.text(L.$("active-target"),session?.target!=null?(session.mode==="power"?`${session.target} / 9`:`${session.target} °C`):targetLabel(requested));L.text(L.$("active-sensor"),heater.active_sensor?.value_c==null?"–":L.temperature(heater.active_sensor.value_c));const temperatureMode=(session?.mode||requested.mode)!=="power";L.$("adjust-target").classList.toggle("hidden",!temperatureMode);L.$("target-adjust-panel").classList.add("hidden");L.$("quick-start").disabled=!status.configuration?.timer_start_allowed||active;L.$("configure-start").disabled=!status.configuration?.timer_start_allowed||active;renderTemperature("roof_tent","roof");renderTemperature("cabin","cabin");renderTemperature("outside","outside");renderNextTimer(status.scheduler?.next_occurrence);renderWarnings(status.warnings)}
async function act(action,message){if(L.state.busy)return;L.state.busy=true;try{await action();L.toast(L.t(message));await L.loadStatus()}catch(error){L.toast(error.message||L.t("requestFailed"),true)}finally{L.state.busy=false}}
function prepareStartDialog(){const settings=L.state.settings?.heater||{};const quick=settings.quick_start||{};const mode=quick.mode||"roof_tent_temperature";const radio=document.querySelector(`#start-form input[name=mode][value="${mode}"]`);if(radio)radio.checked=true;L.$("start-target").value=quick.target_temperature??20;L.$("start-power").value=quick.power_level??5;const maximum=settings.maximum_runtime_minutes||120;const duration=L.$("start-duration");Array.from(duration.options).forEach(option=>option.disabled=Number(option.value)>maximum);duration.value=String(Math.min(quick.runtime_minutes||60,maximum));if(!duration.value){const option=document.createElement("option");option.value=String(maximum);option.textContent=`${maximum} min`;duration.append(option);duration.value=option.value}syncStartFields();L.$("start-dialog").showModal()}
function syncStartFields(){const mode=new FormData(L.$("start-form")).get("mode");L.$("start-target-wrap").classList.toggle("hidden",mode==="power");L.$("start-power-wrap").classList.toggle("hidden",mode!=="power");L.text(L.$("start-target-output"),`${L.$("start-target").value} °C`);L.text(L.$("start-power-output"),`${L.$("start-power").value} / 9`)}
function bind(){L.$("quick-start").addEventListener("click",()=>act(()=>L.mutate("/api/v1/heater/quick-start","POST",{expected_request_revision:L.state.status.heater.request_revision}),"started"));L.$("configure-start").addEventListener("click",prepareStartDialog);document.querySelectorAll("#start-form input[name=mode]").forEach(n=>n.addEventListener("change",syncStartFields));L.$("start-target").addEventListener("input",syncStartFields);L.$("start-power").addEventListener("input",syncStartFields);L.$("start-form").addEventListener("submit",event=>{event.preventDefault();const mode=new FormData(event.currentTarget).get("mode");const body={expected_request_revision:L.state.status.heater.request_revision,mode,target_temperature:mode==="power"?null:Number(L.$("start-target").value),power_level:mode==="power"?Number(L.$("start-power").value):null,runtime_minutes:Number(L.$("start-duration").value)};L.$("start-dialog").close();act(()=>L.mutate("/api/v1/heater/start","POST",body),"started")});L.$("stop-heater").addEventListener("click",()=>act(()=>L.mutate("/api/v1/heater/stop","POST",undefined,false),"stopped"));L.$("extend-session").addEventListener("click",()=>act(()=>L.mutate("/api/v1/heater/session","PATCH",{expected_request_revision:L.state.status.heater.request_revision,target_temperature:null,extend_minutes:15}),"extended"));L.$("adjust-target").addEventListener("click",()=>{const requested=L.state.status.heater.requested;L.$("adjust-target-range").value=requested.target_temperature??20;L.text(L.$("adjust-target-output"),`${L.$("adjust-target-range").value} °C`);L.$("target-adjust-panel").classList.toggle("hidden")});L.$("adjust-target-range").addEventListener("input",()=>L.text(L.$("adjust-target-output"),`${L.$("adjust-target-range").value} °C`));L.$("apply-target").addEventListener("click",()=>act(()=>L.mutate("/api/v1/heater/session","PATCH",{expected_request_revision:L.state.status.heater.request_revision,target_temperature:Number(L.$("adjust-target-range").value),extend_minutes:0}),"targetChanged"))}
L.modules.home={render,bind};
})();
