"use strict";
(function(){
const L=window.Landy;
function rows(node,values){L.definition(node,values)}
function render(settings){if(!settings)return;const heater=settings.heater||{},quick=heater.quick_start||{};L.$("setting-mode").value=quick.mode||"roof_tent_temperature";L.$("setting-target").value=quick.target_temperature??20;L.$("setting-power").value=quick.power_level??5;L.$("setting-runtime").value=quick.runtime_minutes??60;L.$("setting-maximum").value=heater.maximum_runtime_minutes??120;syncMode();const network=settings.network||{},ap=network.access_point||{},known=network.known_networks||[];rows(L.$("network-settings"),[[L.t("apAddress"),ap.ssid||"Landy Heater"],[L.t("station"),network.hostname||"heater"],[L.t("knownNetworks"),String(known.length)],[L.t("configuration"),L.t("readOnlyPhase10")]]);const assignments=settings.sensors?.assignments||{};rows(L.$("sensor-settings"),[[L.t("roofTent"),assignments.roof_tent||"–"],[L.t("cabin"),assignments.cabin||"–"],[L.t("outside"),assignments.outside||"–"]]);rows(L.$("runtime-settings"),[[L.t("defaultRuntime"),L.minutes(quick.runtime_minutes)],[L.t("maxRuntime"),L.minutes(heater.maximum_runtime_minutes)],[L.t("timers"),String(L.state.timers?.total??"–")]]);const time=settings.time||{};rows(L.$("time-settings"),[[L.t("timezone"),time.timezone_name||"–"],[L.t("configuration"),time.timezone_rule||"–"]]);rows(L.$("system-settings"),[[L.t("setup"),settings.system?.setup_complete?L.t("complete"):L.t("incomplete")],[L.t("generation"),String(settings.generation??"–")],[L.t("restartRequired"),L.boolean(settings.restart_required)],[L.t("language"),L.t("browserOnly")]])}
function renderStatus(status){if(!status)return;const network=status.network?.state||{},ap=network.access_point||{},station=network.station||{};rows(L.$("network-settings"),[[L.t("apAddress"),ap.ip||"–"],[L.t("clients"),String(ap.clients??0)],[L.t("station"),station.connected?(station.ssid||L.t("online")):L.t("offline")],[L.t("knownNetworks"),String(station.known_networks?.length??0)],[L.t("configuration"),L.t("readOnlyPhase10")]]);const temperatures=status.temperatures||{};rows(L.$("sensor-settings"),[[L.t("roofTent"),`${L.temperature(temperatures.roof_tent?.value_c)} · ${L.health(temperatures.roof_tent?.health)}`],[L.t("cabin"),`${L.temperature(temperatures.cabin?.value_c)} · ${L.health(temperatures.cabin?.health)}`],[L.t("outside"),`${L.temperature(temperatures.outside?.value_c)} · ${L.health(temperatures.outside?.health)}`]]);const time=status.time||{};rows(L.$("time-settings"),[[L.t("clock"),time.valid?L.t("valid"):L.t("invalid")],[L.t("timezone"),time.timezone||"–"],["RTC",time.rtc_health||"–"]])}
function syncMode(){const power=L.$("setting-mode").value==="power";L.$("setting-target").disabled=power;L.$("setting-power").disabled=!power}
async function save(event){event.preventDefault();const mode=L.$("setting-mode").value,maximum=Number(L.$("setting-maximum").value),runtime=Number(L.$("setting-runtime").value);const heater={maximum_runtime_minutes:maximum,quick_start:{mode,target_temperature:mode==="power"?null:Number(L.$("setting-target").value),power_level:mode==="power"?Number(L.$("setting-power").value):null,runtime_minutes:runtime}};try{await L.mutate("/api/v1/settings","PATCH",{heater});L.toast(L.t("saved"));await Promise.all([L.loadSettings(),L.loadStatus()])}catch(error){L.toast(error.message||L.t("requestFailed"),true)}}
function bind(){L.$("setting-mode").addEventListener("change",syncMode);L.$("heater-settings").addEventListener("submit",save);L.$("language").addEventListener("change",event=>L.applyLanguage(event.target.value));L.$("load-diagnostics").addEventListener("click",async()=>{const output=L.$("diagnostics-output");output.textContent="…";try{const data=await L.request("/api/v1/diagnostics");output.textContent=JSON.stringify(data,null,2)}catch(error){output.textContent=error.message||L.t("requestFailed")}})}
L.modules.settings={render,renderStatus,bind};
})();
