"use strict";
(function(){
const L=window.Landy,weekdayKeys=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"];
const dayLabel=days=>(days||[]).map(day=>L.t(weekdayKeys[day])).join(" · ");
const targetLabel=timer=>timer.mode==="power"?`${L.t("power")} ${timer.power_level}/9`:`${timer.target_temperature} °C`;
function button(label,action,className="secondary"){const n=L.el("button",`button ${className} compact`,label);n.type="button";n.addEventListener("click",action);return n}
function card(timer){const article=L.el("article",`card timer-card${timer.enabled?"":" disabled"}`),header=L.el("header"),title=L.el("div"),actions=L.el("div","timer-actions");title.append(L.el("h2",null,timer.name),L.el("div","time",timer.start));header.append(title,L.el("span",`badge ${timer.enabled?"ok":"neutral"}`,L.t(timer.enabled?"active":"inactive")));const meta=L.el("div","timer-meta");[dayLabel(timer.weekdays),L.mode(timer.mode),targetLabel(timer),L.minutes(timer.runtime_minutes)].forEach(value=>meta.append(L.el("span",null,value)));actions.append(button(timer.enabled?L.t("inactive"):L.t("active"),()=>toggle(timer)),button(L.t("edit"),()=>openDialog(timer)),button(L.t("delete"),()=>remove(timer),"secondary"));article.append(header,meta,actions);return article}
function render(data){if(!data)return;const list=L.$("timer-list");list.replaceChildren();if(!data.items?.length)list.append(L.el("article","card empty",L.t("noTimer")));else data.items.forEach(timer=>list.append(card(timer)));const page=Math.floor((data.offset||0)/(data.limit||8))+1,total=Math.max(1,Math.ceil((data.total||0)/(data.limit||8)));L.text(L.$("timers-page"),`${L.t("page")} ${page} / ${total}`);L.$("timers-prev").disabled=data.offset<=0;L.$("timers-next").disabled=data.offset+data.limit>=data.total}
async function mutate(action,message){if(L.state.busy)return;L.state.busy=true;try{await action();L.toast(L.t(message));await Promise.all([L.loadTimers(L.state.timers?.offset||0),L.loadStatus()])}catch(error){L.toast(error.message||L.t("requestFailed"),true)}finally{L.state.busy=false}}
function toggle(timer){const next={...timer,enabled:!timer.enabled};mutate(()=>L.mutate(L.timerPath(timer.id),"PUT",next),"saved")}
function remove(timer){if(!confirm(L.t("confirmDelete")))return;mutate(()=>L.mutate(L.timerPath(timer.id),"DELETE",undefined),"deleted")}
function syncTarget(){const power=L.$("timer-mode").value==="power",input=L.$("timer-target");input.min=power?"1":"5";input.max=power?"9":"30";if(Number(input.value)<Number(input.min)||Number(input.value)>Number(input.max))input.value=power?"5":"20"}
function openDialog(timer=null){L.text(L.$("timer-dialog-title"),L.t(timer?"editTimer":"addTimer"));L.$("timer-id").value=timer?.id||"";L.$("timer-name").value=timer?.name||"";L.$("timer-time").value=timer?.start||"07:00";L.$("timer-mode").value=timer?.mode||"roof_tent_temperature";L.$("timer-target").value=timer?(timer.mode==="power"?timer.power_level:timer.target_temperature):20;L.$("timer-runtime").value=timer?.runtime_minutes||60;L.$("timer-runtime").max=L.state.settings?.heater?.maximum_runtime_minutes||120;L.$("timer-enabled").checked=timer?.enabled??true;document.querySelectorAll("#timer-weekdays input").forEach(n=>n.checked=timer?timer.weekdays.includes(Number(n.value)):Number(n.value)<5);syncTarget();L.$("timer-dialog").showModal()}
function timerFromForm(){const mode=L.$("timer-mode").value;let id=L.$("timer-id").value;if(!id)id=`timer-${Date.now().toString(36)}`;const weekdays=Array.from(document.querySelectorAll("#timer-weekdays input:checked"),n=>Number(n.value));if(!weekdays.length)throw new Error(L.t("weekdays"));return{id,name:L.$("timer-name").value.trim(),enabled:L.$("timer-enabled").checked,weekdays,start:L.$("timer-time").value,mode,target_temperature:mode==="power"?null:Number(L.$("timer-target").value),power_level:mode==="power"?Number(L.$("timer-target").value):null,runtime_minutes:Number(L.$("timer-runtime").value)}}
function bind(){const picker=L.$("timer-weekdays");weekdayKeys.forEach((key,index)=>{const label=L.el("label"),input=document.createElement("input");input.type="checkbox";input.value=String(index);label.append(input,L.el("span",null,L.t(key)));picker.append(label)});L.$("add-timer").addEventListener("click",()=>openDialog());L.$("timer-mode").addEventListener("change",syncTarget);L.$("timer-form").addEventListener("submit",event=>{event.preventDefault();let timer;try{timer=timerFromForm()}catch(error){L.toast(error.message,true);return}const editing=Boolean(L.$("timer-id").value);L.$("timer-dialog").close();mutate(()=>L.mutate(editing?L.timerPath(timer.id):"/api/v1/timers",editing?"PUT":"POST",timer),"saved")});L.$("timers-prev").addEventListener("click",()=>L.loadTimers(Math.max(0,L.state.timers.offset-8)).catch(error=>L.toast(error.message,true)));L.$("timers-next").addEventListener("click",()=>L.loadTimers(L.state.timers.offset+8).catch(error=>L.toast(error.message,true)))}
L.modules.timers={render,bind};
})();
